# Generated by Django 6.0.6 on 2026-06-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('quote', 'Quote'), ('list', 'List'), ('code', 'Code Block'), ('card', 'Card'), ('table', 'Table')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('heading_level', models.PositiveSmallIntegerField(default=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/blocks/')),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('code_language', models.CharField(blank=True, max_length=30)),
                ('data', models.JSONField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
